apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.inputs.blogService.name }}
spec:
  type: {{ .Values.inputs.blogService.type }}
  selector: {{- include "blog-chart.blogDeployLabels" . | indent 4 }}
  ports:
  - port: {{ .Values.inputs.blogService.ports.port }}
    targetPort: {{ .Values.inputs.blogService.ports.targetPort }}