apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.inputs.dbService.name }}
spec:
  type: {{ .Values.inputs.dbService.type }}
  selector: {{- include "blog-chart.dbDeployLabels" . | indent 4 }}
  ports:
  - port: {{ .Values.inputs.dbService.ports.port }}
    targetPort: {{ .Values.inputs.dbService.ports.targetPort }}